version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - docker build -t REPOSITORY_NAME_PLACEHOLDER:IMAGE_TAG_PLACEHOLDER .
      - docker tag REPOSITORY_NAME_PLACEHOLDER:IMAGE_TAG_PLACEHOLDER REPOSITORY_URI_PLACEHOLDER

  post_build:
    commands:
      - docker push REPOSITORY_URI_PLACEHOLDER
      - printf '[{"name":"CONTAINER_NAME_PLACEHOLDER","imageUri":"%s"}]' REPOSITORY_URI_PLACEHOLDER > imagedefinitions.json

artifacts:
  files: imagedefinitions.json